=== ViktorFP/XMLTask/src/Airlines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.example.org/Airlines" 
xmlns:tns="http://www.example.org/Airlines">
	
	<element name="Airlines">
		<complexType>
			<sequence>
				<element name="Airline" type="tns:Airline"
				minOccurs="1" maxOccurs="unbounded"/>
			</sequence>			
		</complexType>
	</element>
	
	<complexType name="Airline">
		<sequence>
			<element name="Schedule" type="tns:Schedule"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="counrty" type="string" use="required"/>
	</complexType>
	
	<complexType name="Schedule">
		<sequence>
			<element name="FlightSegment" type="tns:FlightSegment"
			minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="FlightSegment">
		<sequence>
			<element name="DepartureAirport" type="tns:DepartureAirport"/>
			<element name="ArrivalAirport" type="tns:ArrivalAirport"/>
			<element name="OperatingAirline" type="tns:OperatingAirline"/>
		</sequence>		
		<attribute name="DepartureDateTime" type="dateTime" use="required"/>
		<attribute name="ArrivalDateTime" type="dateTime" use="required"/>
		<attribute name="FlightNumber" type="string" use="required"/>
	</complexType>
	<complexType name="DepartureAirport">
		<attribute name="LocationCode" type="string" use="required"/>
		<attribute name="CodeContext" type="string" use="required"/>
	</complexType>
	<complexType name="ArrivalAirport">
		<attribute name="LocationCode" type="string" use="required"/>
		<attribute name="CodeContext" type="string" use="required"/>
	</complexType>
	<complexType name="OperatingAirline">
		<attribute name="Code" type="string" use="required"/>
	</complexType>
</schema>

=== ViktorFP/XMLTask/src/testFile.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><tns:Airlines xmlns:tns="http://www.example.org/Airlines" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Airlines Airlines.xsd"><Airline counrty="England" name="airline1"><Schedule><FlightSegment ArrivalDateTime="2016-03-08T07:16:00.000+03:00" DepartureDateTime="2016-03-08T06:10:00.000+03:00" FlightNumber="2818"><DepartureAirport CodeContext="IATA" LocationCode="JFK"/><ArrivalAirport CodeContext="IATA" LocationCode="BOS"/><OperatingAirline Code="B6"/></FlightSegment><FlightSegment ArrivalDateTime="2016-03-18T07:16:00.000+03:00" DepartureDateTime="2016-03-18T06:15:00.000+03:00" FlightNumber="4858"><DepartureAirport CodeContext="TDP" LocationCode="JDK"/><ArrivalAirport CodeContext="TDP" LocationCode="BOS"/><OperatingAirline Code="ADT"/></FlightSegment></Schedule></Airline><Airline counrty="American" name="airline2"><Schedule><FlightSegment ArrivalDateTime="2016-03-18T07:16:00.000+03:00" DepartureDateTime="2016-03-18T06:15:00.000+03:00" FlightNumber="2858"><DepartureAirport CodeContext="TDP" LocationCode="JDK"/><ArrivalAirport CodeContext="TDP" LocationCode="BOS"/><OperatingAirline Code="ADT"/></FlightSegment></Schedule></Airline></tns:Airlines>

=== ViktorFP/XMLTask/src/Airlines.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Airlines
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:tns="http://www.example.org/Airlines"
xsi:schemaLocation="http://www.example.org/Airlines Airlines.xsd">
	
	<Airline name="airline1" counrty="England">
		<Schedule>
			<FlightSegment DepartureDateTime="2016-03-08T06:10:00.000" ArrivalDateTime="2016-03-08T07:16:00.000" FlightNumber="2818">
				<DepartureAirport LocationCode="JFK" CodeContext="IATA"/>
				<ArrivalAirport LocationCode="BOS" CodeContext="IATA"/>
				<OperatingAirline Code="B6"/>
			</FlightSegment>	
			<FlightSegment DepartureDateTime="2016-03-18T06:15:00.000" ArrivalDateTime="2016-03-18T07:16:00.000" FlightNumber="4858">
				<DepartureAirport LocationCode="JDK" CodeContext="TDP"/>
				<ArrivalAirport LocationCode="BOS" CodeContext="TDP"/>
				<OperatingAirline Code="ADT"/>
			</FlightSegment>
		</Schedule>
	</Airline>
	<Airline name="airline2" counrty="American">
		<Schedule>
			<FlightSegment DepartureDateTime="2016-03-18T06:15:00.000" ArrivalDateTime="2016-03-18T07:16:00.000" FlightNumber="2858">
				<DepartureAirport LocationCode="JDK" CodeContext="TDP"/>
				<ArrivalAirport LocationCode="BOS" CodeContext="TDP"/>
				<OperatingAirline Code="ADT"/>
			</FlightSegment>			
		</Schedule>
	</Airline>
</tns:Airlines>
